version: '3.3'

services:
  mongo-system:
    image: mongo
    volumes:
      - ./data:/data/db/system
    ports:
- "27017:27017"

  mongo-2hours:
    image: mongo
    volumes:
      - ./data:/data/db/2hours
    ports:
      - "27018:27017"
  
  mongo-4hours:
    image: mongo
    volumes:
      - ./data:/data/db/4hours
    ports:
      - "27019:27017"
  
  mongo-6hours:
    image: mongo
    volumes:
      - ./data:/data/db/6hours
    ports:
      - "27020:27017"
  
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo-system

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data/db/cache
