version: '3.3'

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data/cache
